import eslint from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

// 浏览器和扩展环境的全局变量
const browserGlobals = {
  chrome: 'readonly',
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Image: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLInputElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  NodeListOf: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  PerformanceObserver: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  getComputedStyle: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  encodeURIComponent: 'readonly',
  decodeURIComponent: 'readonly',
  parseInt: 'readonly',
  parseFloat: 'readonly',
  isNaN: 'readonly',
  isFinite: 'readonly',
  Infinity: 'readonly',
  NaN: 'readonly',
  undefined: 'readonly',
  Math: 'readonly',
  Date: 'readonly',
  Array: 'readonly',
  Object: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  Symbol: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  Promise: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  JSON: 'readonly',
  RegExp: 'readonly',
  Error: 'readonly',
  TypeError: 'readonly',
  RangeError: 'readonly',
  SyntaxError: 'readonly',
  ReferenceError: 'readonly',
  URIError: 'readonly',
  EvalError: 'readonly',
  Intl: 'readonly',
  DataView: 'readonly',
  ArrayBuffer: 'readonly',
  Int8Array: 'readonly',
  Uint8Array: 'readonly',
  Uint8ClampedArray: 'readonly',
  Int16Array: 'readonly',
  Uint16Array: 'readonly',
  Int32Array: 'readonly',
  Uint32Array: 'readonly',
  Float32Array: 'readonly',
  Float64Array: 'readonly',
  BigInt: 'readonly',
  BigInt64Array: 'readonly',
  BigUint64Array: 'readonly',
};

export default [
  eslint.configs.recommended,
  // TypeScript 文件配置
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
      globals: {
        ...browserGlobals,
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        exports: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      'no-console': 'off',
    },
  },
  // JavaScript 文件配置 (content scripts 等浏览器扩展代码)
  {
    files: ['content/**/*.js', 'background/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: browserGlobals,
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'off', // 浏览器环境有很多全局变量
      'no-unused-vars': 'warn', // 降级为警告
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**', 'tests/**', 'website/**', 'local-node/**', 'eslint.config.js', 'vite.config.ts', 'vitest.config.ts'],
  },
];
