/**
 * AI Chat Exporter - PDF Formatter
 * 使用浏览器原生打印功能生成 PDF
 */

import type { ChatMessage, ExportMetadata } from '../../types';
import type { FormatterDefinition } from './registry';
import { registerFormat } from './registry';

const pdfFormatter: FormatterDefinition = {
  id: 'pdf',
  name: 'PDF',
  extension: 'pdf',
  mimeType: 'application/pdf',

  /**
   * PDF 导出返回 HTML 内容，由调用方打开打印对话框
   */
  format(messages: ChatMessage[], metadata: ExportMetadata = {}): string {
    return generatePrintableHTML(messages, metadata);
  },
};

/**
 * 生成用于打印/PDF的 HTML 内容
 */
export function generatePrintableHTML(
  messages: ChatMessage[],
  metadata: ExportMetadata = {}
): string {
  const title = metadata.title || 'Chat Export';
  const source = metadata.source || 'AI Chat';
  const exportedAt = new Date().toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #e5e5e5;
    }

    .header h1 {
      font-size: 24px;
      margin-bottom: 10px;
    }

    .header .meta {
      color: #666;
      font-size: 14px;
    }

    .badge {
      display: inline-block;
      background: #10a37f;
      color: white;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 12px;
      margin-top: 10px;
    }

    .messages {
      margin-bottom: 40px;
    }

    .message {
      margin-bottom: 24px;
      padding: 16px;
      border-radius: 8px;
      page-break-inside: avoid;
    }

    .message.user {
      background: #f0f7ff;
      border-left: 4px solid #2563eb;
    }

    .message.assistant {
      background: #f7f7f8;
      border-left: 4px solid #10a37f;
    }

    .message-header {
      font-weight: 600;
      margin-bottom: 8px;
      font-size: 14px;
    }

    .message.user .message-header {
      color: #2563eb;
    }

    .message.assistant .message-header {
      color: #10a37f;
    }

    .message-content {
      white-space: pre-wrap;
      word-wrap: break-word;
      font-size: 14px;
    }

    .message-content code {
      background: #e5e5e5;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
      font-size: 13px;
    }

    .message-content pre {
      background: #f7f7f8;
      padding: 12px;
      border-radius: 6px;
      overflow-x: auto;
      margin: 10px 0;
      border: 1px solid #e5e5e5;
    }

    .message-content pre code {
      background: none;
      padding: 0;
    }

    .footer {
      text-align: center;
      padding-top: 20px;
      border-top: 1px solid #e5e5e5;
      color: #666;
      font-size: 12px;
    }

    @media print {
      body {
        padding: 20px;
      }

      .message {
        break-inside: avoid;
      }

      .no-print {
        display: none !important;
      }
    }

    .print-btn {
      position: fixed;
      top: 20px;
      right: 20px;
      background: #10a37f;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 8px;
      font-size: 14px;
      cursor: pointer;
      box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    }

    .print-btn:hover {
      background: #0d8a6a;
    }

    @media print {
      .print-btn {
        display: none !important;
      }
    }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">🖨️ Save as PDF</button>

  <header class="header">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">
      Source: ${escapeHtml(source)} • ${escapeHtml(exportedAt)} • ${messages.length} messages
    </div>
    <div class="badge">Exported by AI Chat Exporter</div>
  </header>

  <main class="messages">
${messages.map((msg) => formatPrintMessage(msg)).join('\n')}
  </main>

  <footer class="footer">
    <p>Generated by AI Chat Exporter • ${new Date().toISOString()}</p>
  </footer>
</body>
</html>`;
}

/**
 * 格式化打印消息
 */
function formatPrintMessage(msg: ChatMessage): string {
  const isUser = msg.role === 'user';
  const roleClass = isUser ? 'user' : 'assistant';
  const roleIcon = isUser ? '👤' : '🤖';
  const roleName = isUser ? 'You' : 'AI';

  return `    <article class="message ${roleClass}">
      <div class="message-header">${roleIcon} ${roleName}</div>
      <div class="message-content">${formatPrintContent(msg.content)}</div>
    </article>`;
}

/**
 * 格式化打印内容
 */
function formatPrintContent(content: string): string {
  let formatted = escapeHtml(content);

  // 处理代码块
  formatted = formatted.replace(
    /```(\w*)\n([\s\S]*?)```/g,
    '<pre><code>$2</code></pre>'
  );

  // 处理行内代码
  formatted = formatted.replace(/`([^`]+)`/g, '<code>$1</code>');

  return formatted;
}

/**
 * 转义 HTML
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}

/**
 * 在新窗口中打开打印对话框
 */
export function openPrintDialog(messages: ChatMessage[], metadata: ExportMetadata = {}): void {
  const html = generatePrintableHTML(messages, metadata);
  const printWindow = window.open('', '_blank');

  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();

    // 自动触发打印（延迟以确保内容加载完成）
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 500);
    };
  }
}

registerFormat(pdfFormatter);

export { pdfFormatter };
